export const QUESTIONS_PER_PAGE = 6

export const suitabilityQuestionList = [
  { name: 'q1', title: 'オフィスに行く' },
  { name: 'q2', title: '研究職' },
  { name: 'q3', title: '建設とエンジニアリング' },
  { name: 'q4', title: 'クリエイティブな写真' },
  { name: 'q5', title: '競売人' },
  {
    name: 'q6',
    title: '教師'
  },
  { name: 'q7', title: 'メカニック' },
  { name: 'q8', title: '化学者' },
  { name: 'q9', title: '監視と記録' },
  { name: 'q10', title: '売って説得する' },
  { name: 'q11', title: 'デザインとペイント' },
  { name: 'q12', title: '助けとケア' },
  { name: 'q13', title: 'ソーシャルワーカー' },
  { name: 'q14', title: '管理者' },
  { name: 'q15', title: '消防士' },
  { name: 'q16', title: 'マネージャー' },
  { name: 'q17', title: 'ジュエリー制作' },
  { name: 'q18', title: '子供たちを導く' },
  { name: 'q19', title: '医療診断' },
  { name: 'q20', title: 'メモを取る' },
  { name: 'q21', title: 'スケッチとデザイン' },
  { name: 'q22', title: '移動式整備士' },
  { name: 'q23', title: 'ヘルプが無効' },
  { name: 'q24', title: 'ビジネスマネージャー' },
  { name: 'q25', title: '勉強' },
  { name: 'q26', title: 'スタイリングと装飾' },
  { name: 'q27', title: 'ビジネス取引を成立させる' },
  { name: 'q28', title: '修正する' },
  { name: 'q29', title: 'ソーシャルカウンセラー' },
  { name: 'q30', title: '分子科学者' },
  { name: 'q31', title: '会計士' },
  { name: 'q32', title: '獣医' },
  { name: 'q33', title: '会長' },
  { name: 'q34', title: '管理' },
  { name: 'q35', title: '知識を得る' },
  { name: 'q36', title: 'ランドスケープアーキテクチャ' },
  { name: 'q37', title: '歯科技工士' },
  { name: 'q38', title: 'ホスト' },
  { name: 'q39', title: '描く' },
  { name: 'q40', title: '案内係' },
  { name: 'q41', title: 'コントローラ' },
  { name: 'q42', title: '株式仲買人' },
  { name: 'q43', title: 'データアナリスト' },
  { name: 'q44', title: 'エンジニア' },
  { name: 'q45', title: '科学' },
  { name: 'q46', title: 'ツール' },
  { name: 'q47', title: '医療サポート' },
  { name: 'q48', title: '芸術と演劇' },
  { name: 'q49', title: '論理的推論' },
  { name: 'q50', title: '整理と整理' },
  { name: 'q51', title: '道案内をする' },
  { name: 'q52', title: '教えたり説明したりする' },
  { name: 'q53', title: '高齢者介護' },
  { name: 'q54', title: '不動産業者' },
  { name: 'q55', title: 'ファッションデザイナー' },
  { name: 'q56', title: '問題解決' },
  { name: 'q57', title: 'エレクトロニクス' },
  { name: 'q58', title: '創作文' },
  { name: 'q59', title: 'アーカイブ' },
  { name: 'q60', title: '営業担当者' }
]
